### PR TITLE
Edit ticket controller

### PR DESCRIPTION
**Pull request by silvermist**
editing the view for all tickets in the all tickets view :
    1)view the fields
    2)handle previous error on having no tickets
@LinKassem @MariamMohamedFawzy @mansoursaid001

### CODE REVIEW

**Comment by marmohamed** [comment]
@silvermist 
with one ticket in the database ->
screen shot 2016-05-03 at 11 44 28 pm

screen shot 2016-05-03 at 11 44 31 pm

without any tickets -> mafeesh moshkla

**Comment by silvermist** [comment]
@MariamMohamedFawzy  ta2reban l moshkla f 7aga tanya 
l ticket di fi 7aga fl attributes fadya sa7 ?

**Comment by silvermist** [comment]
@MariamMohamedFawzy  i added a change , could you try again ? :D

**Comment by marmohamed** [comment]
@silvermist  7elw (Y), but changing the status does not work correctly 3andy, msh 3arfa leeh

**Comment by silvermist** [comment]
@MariamMohamedFawzy ana l mfrod m3'yrthash hya di l adima :D , mot2kda mn 7war l arqam 0,1,2 ? :D

**Comment by silvermist** [comment]
@MariamMohamedFawzy  please recheck

**Pull request merged**
