### PR TITLE
Ticket status functions

### PR DESCRIPTION
**Pull request by silvermist**
@LinKassem @mansoursaid001 @MariamMohamedFawzy

### CODE REVIEW

**Comment by MariamMohamedFawzy** [comment]
@silvermist how to test?

**Comment by marmohamed** [comment]
@silvermist how can i test it?

**Comment by silvermist** [comment]
from the sidebar all tickets should redirect to the view where it contains "all tickets" then from there you will find the change status drop down list

**Comment by marmohamed** [comment]
@silvermist I can change the status from /tickets/1/edit but the /tickets only shows the status without being able to change it, is this ok?

**Comment by silvermist** [comment]
you should be able to do so from the drop down list ! :D 
in the ALL tickets where all the tickets exist there is a new column which is the status where you can change it

**Comment by marmohamed** [comment]
msh sha8ala 3andy

**Comment by marmohamed** [comment]
@LinKassem may u test it?

**Pull request merged**
