### PR TITLE
reply to ticket

### PR DESCRIPTION
**Pull request by marmohamed**
@LinKassem @silvermist @mansoursaid001

### CODE REVIEW

**Comment by LinKassem** [comment]
@MariamMohamedFawzy Thank you!
I navigated to /home and I clicked on the small watch and indeed a ticket was created (Y) :D what should I also test?

**Comment by marmohamed** [comment]
@LinKassem @silvermist

**Comment by LinKassem** [comment]
@MariamMohamedFawzy  I am facing the same problem unfortunatly.

@silvermist  can you please review?

to test
1) login as an admin
2) go to /home
3) try to click on a tweet..it will open a form on the right hand side
4) if you try to click on the same tweet again an error message will appear
5) fill the form on the right hand side and submit
6) you will be redirected to ticket.show view where you can see the tweet and reply to it

Thank you!

**Comment by silvermist** [comment]
@MariamMohamedFawzy 
it doesn't redirect to "show",  it gives an alert that the ticket was opened though

also i have a comment on the status part, it should be 0,1,2 to be consistent with the rest of the app i guess according to the modifications...

**Comment by marmohamed** [comment]
It should not redirect to show, The user should be in the same page, lin etafa2et ma3aya 3ala kda

**Comment by silvermist** [comment]
@MariamMohamedFawzy  i was considering point 6) that @LinKassem  wrote :D !
tb hwa b3d ma y redirect 3la same view i should be able to reply on it ?

**Comment by marmohamed** [comment]
@silvermist no , we assume that the user should be able to mark multiple tweets without redirection, if u wanna reply, u will go to all tickets and select that specific ticket

**Comment by silvermist** [comment]
@MariamMohamedFawzy 
tb tmam and the reply part should be in this task brdo ?

**Comment by marmohamed** [comment]
@silvermist  yes

**Comment by silvermist** [comment]
(Y)

**Pull request merged**
