### PR TITLE
Adding image upload for changing logo

### PR DESCRIPTION
**Pull request by mansoursaid**
uploading image code with a sample form and route

### CODE REVIEW

**Comment by LinKassem** [comment]
@mansoursaid001 Can you please : 

1) The image is not showing after I press submit, I know that a success message is shown but where is the image itself? 

2) Make sure that the 'route' and the 'view' are adjusted to match the view/page in 'http://localhost:8000/app_settings' (I think the show view, I am not sure). 

3) Fix the merge conflicts

When you are done mention me. Thank you!

**Comment by mansoursaid** [comment]
1- The image is in the public folder. I didn't know where to put it so I put it there. I need to know how the app logo is retrieved in order to put it there.
Also I had in mind that we can put the app settings in a table and retrieve things from there, like the app logo file name for example
2- the app_settings view just crashes with a lot of error, is that normal?
@LinKassem

**Comment by LinKassem** [comment]
@mansoursaid001 
1- Okay so the image uploads correctly to the public folder, you just need to embed in in the views 
check this link out : http://stackoverflow.com/questions/29858097/laravel-blade-html-image

2- app_settings table, @MariamMohamedFawzy  have worked on the app_settings part before. Maybe you can discuss it together. Although, in my opinion since Maryam has already implemented this part and it has been tested, lets leave it as it is an move on to another story.

3- I don't know why the app is crashing with you :( I have just pulled the development branch and went to /app_settings and it is working fine. try running composer update maybe?

**Comment by mansoursaid** [comment]
@LinKassem I tried shoofy if this is good wla la2
lw 3andek ay tips aw keda :D 
w ah btw i need el image size elly fel html 3shan a-resize ay image akbar 3shan m3rftesh awsalaha :D

**Comment by LinKassem** [comment]
@mansoursaid001 Awesome! I have added very small inline styles.
-image size can be  40x40 maybe

**Comment by mansoursaid** [comment]
@LinKassem made the size fixed from the HTML. couldn't do it from laravel. check and tell me if it is right

**Comment by LinKassem** [comment]
@mansoursaid001 Awesome! Thank you

**Pull request merged**
