### PR TITLE
Tickets per agent

### PR DESCRIPTION
**Pull request by silvermist**
@MariamMohamedFawzy this is to view the number of tickets under each status for the users
to test  for example got to /supervisors or /admins

### CODE REVIEW

**Comment by marmohamed** [comment]
@silvermist @LinKassem msh mazboot el backend, for an agent with 1 open, 1 closed, 1 in progress
I get 2 open , 0 closed, 0 in progress

**Comment by silvermist** [comment]
@MariamMohamedFawzy  why would the relation table be inconsistent ? :(

**Comment by LinKassem** [comment]
@MariamMohamedFawzy Done. (Y)!

**Comment by silvermist** [comment]
boo

**Pull request merged**
